### PR TITLE
Bullet point

### PR DESCRIPTION
**Pull request by Spider2man3**
Fixes the issue with the bullet point not acting like a normal one. Lets the cursor jump around the bullet point.

### CODE REVIEW

**Comment by Deadpikle** [comment]
Will look at this when https://github.com/Deadpikle/macOS-Rich-Text-Editor/pull/5 is merged.

**Comment by Deadpikle** [comment]
Once you carry over the same changes from the macOS repo, this should be good to go after a test.

**Comment by Spider2man3** [comment]
Please take a look at this and see if it works as should be. I have tested it and I think it is ready to go. Let me know if you find any bugs

**Comment by Deadpikle** [comment]
Sorry, there is at least one regression.

In the following example, the `|` character represents the caret/selection.
Case:
```
* hi 
* mom| 
* dad
```

Hit enter. Expect:
```
* hi
* mom
* |
* dad
```

What we get:
```
* hi
* mom

* |dad
```

**Comment by Deadpikle** [comment]
There is also a bug with the arrow key movement:

Case:
```
blah blah blah

* hi|
* mom
```

Hit the up arrow key. Expect:

```
blah blah blah
|
* hi
* mom
```

Get:
```
blah blah blah

* |hi
* mom
```

In addition, after hitting up again, I'd expect to be on the empty line. What ends up happening is I end up in the previous paragraph.

**Comment by Spider2man3** [comment]
Selection problems fixed. However if you were to do this
```
blah blah blah

* hi
* mo|m
* dad
```
Hit the enter key. Expect:
```
blah blah blah

* hi
* mo
* |m
* dad
```
Get:
```
blah blah blah

* hi
* mo
|m
* dad
```
To fix this, I have to comment out Line 1195-1197:
```
if (rangeOfCurrentParagraph.length != 0) {
	return;
}
```
But this cause some very interesting errors.

**Comment by Deadpikle** [comment]
It's been over a year since the original PR. Do you plan to finish this?

**Pull request merged**
