### PR TITLE
Try to resize image attachment display size.

### PR DESCRIPTION
**Pull request by hstdt**
To show large size images, here's my idea of resize.

### CODE REVIEW

**Comment by hstdt** [comment]
Before:
richtexteditorbefore
After:
richtexteditordemo

**Comment by Deadpikle** [comment]
👍

**Comment by Deadpikle** [comment]
In the future, though, be a bit careful about your pull requests -- your changes in `RichTextEditor.m` from #8 showed up here!

**Comment by hstdt** [comment]
@Deadpikle 

When saving attributedString to rtfd data,`attachmentBoundsForTextContainer ` in `RichTextImageAttachment`will lost, but `NSKeyedArchiver` works well(slower).

Maybe this is not the best way of solving image size..😓

image

image

**Comment by Deadpikle** [comment]
@hstdt Perhaps there is something you/we could do with [DTCoreText](https://github.com/Cocoanetics/DTCoreText) to save and load the text with attachment? At the very least, you could save it as HTML more easily that way. Something to look into...hmm...

See #11.

**Pull request merged**
